### ISSUE TITLE
Polygon Connector 

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#126]

**Comment by Lohann** [comment]
@isabellelaususan @dvc94ch 

Polygon has two networks:
- [Polygon PoS](https://polygon.technology/polygon-pos)
- [Polygon ZKevm](https://polygon.technology/polygon-zkevm)
- [Polygon Miden](https://polygon.technology/polygon-miden) (not live yet)

zkevm is pretty new and low in activity, so I assume the plan is supporting the Polygon PoS for now, the good news is that a polygon is Ethereum compatible, the only differences are:

1 - Uses a different consensus [PolyBTF](https://wiki.polygon.technology/docs/supernets/design/consensus/polybft/polybft-protocol/)
2 - Have some specific [Genesis Contracts](https://wiki.polygon.technology/docs/pos/reference/contracts/genesis-contracts)
3 - The recommend client are [Heimdall](https://wiki.polygon.technology/docs/pos/design/heimdall/overview) and [Bor](https://wiki.polygon.technology/docs/pos/design/bor/overview) instead of Go Ethereum.

The RPC methods are the same, once we already support Ethereum this should be very straightforward.

I'm using this RPC provider for development: https://www.ankr.com/rpc/polygon

**Comment by dvc94ch** [comment]
Yeah, the main trouble is extending our testing framework to properly support setting up polygon.

**Comment by Lohann** [comment]
Closed by:
https://github.com/Analog-Labs/chain-connectors/pull/174

The testing will be handle in another task.

**Comment by Lohann** [comment]
Closed by https://github.com/Analog-Labs/chain-connectors/pull/174

The testing will be handle by another task
